### ISSUE TITLE
Missing references in call graph for Java/C#

### ISSUE THREAD

**Issue by LeaoLuciano** [doxygen/doxygen#10281]
**Describe the bug**
Doxyparse addon doesn't show all references because ```MemberDef::getReferencesMembers()``` is not producing the right output for Java/C#  (https://github.com/doxygen/doxygen/blob/d062df6c56464f8063acb4fceb989e0cffdd754a/addon/doxyparse/doxyparse.cpp#L299C1-L299C45).

**Expected behavior**
Running ```doxyparse .``` in https://github.com/analizo/analizo/tree/main/t/samples/deep_inheritance/java using Release 1.9.3 of Doxygen produces the expected output:
```
.
.
.

ShopController.java:
  "ShopController":
    defines:
      - "main()":
          ...
          uses:
            - "name":
                type: variable
                defined_in: "Human"
            - "sellDogTo(Human)":
                type: function
                defined_in: "VenderShop"
VenderShop.java:
  "VenderShop":
    defines:
      - "sellDogTo(Human)":
         ...
          uses:
            - "name":
                type: variable
                defined_in: "Dog"
            - "owner":
                type: variable
                defined_in: "Dog"
            - "pet":
                type: variable
                defined_in: "Human"

```

**To Reproduce**
Running ```doxyparse .``` in https://github.com/analizo/analizo/tree/main/t/samples/deep_inheritance/java using Release 1.9.8 of Doxygen produces a wrong output:
```
.
.
.

ShopController.java:
  "ShopController":
    defines:
      - "main()":
      ...
          uses:
            - "sellDogTo(Human)":
                type: function
                defined_in: "VenderShop"
VenderShop.java:
  "VenderShop":
    defines:
      - "sellDogTo(Human)":
          ...
```

**Version**
Doxygen 1.9.8 (also checked on the latest commit of master d062df6c56).

**Additional context**
A bisect (using [Analizo](https://github.com/analizo/analizo) tests) indicated that the commit https://github.com/doxygen/doxygen/commit/2976b67adcd1e2d3a787533566d93915ea237065 introduced the bug.
