### ISSUE TITLE
C++ using-declaration is not parsed right

### ISSUE THREAD

**Issue by TommyPec** [doxygen/doxygen#10599]
**Describe the bug**
A [using-declaration to inherit constructors](https://en.cppreference.com/w/cpp/language/using_declaration) produces:
- A warning if not documented (and an empty documentation)
- A documentation if documented

**Expected behavior**
No warning, and no function documented.
The syntax is used to modify the visibility of the constructors of the base class, so I don't think that they should be documented.

**Screenshots**
<img width="538" alt="Screenshot 2024-01-27 at 22 37 43" src="https://github.com/doxygen/doxygen/assets/169026/b4788d04-5ff6-43e1-931d-0e596133c436">

**To Reproduce**
[DoxyTest.zip](https://github.com/doxygen/doxygen/files/14074962/DoxyTest.zip)

**Version**
Doxygen 1.10.0, MacOS ARM, installed though Homebrew.

**Stack trace**
No crash

**Additional context**
This problem affects ns-3. Until fixed we're forced to use an old Doxygen version (it's a workaround).
The working Doxygen version is 1.9.6. Sorry if I didn't do a regression test to check if 1.97 was affected.

**Comment by albert-github** [comment]
What is the warning that you get? 
With the 1.9.6 version I get the warning:
```
.../DoxyTest/main.cc:33: warning: Member SpectrumWifiPhy() (function) of class ExtSpectrumWifiPhy is not documented.
```

When setting:
```
WARN_IF_UNDOCUMENTED = NO
```
the warning disappears, so the setting of `WARN_IF_UNDOCUMENTED` is of higher influence than the setting of `WARNINGS`.
@doxygen is this intended / correct?

(Note: I also see the behavior with the current master: 1.11.0 (cf77bce42109695e24e270f57483c83600fb134e))

**Comment by doxygen** [comment]
> the warning disappears, so the setting of WARN_IF_UNDOCUMENTED is of higher influence than the setting of WARNINGS.
@doxygen is this intended / correct?

Yes, this has been like this since the introduction of these more specialized warning options (it can be a bit better documented, especially that WARNINGS=NO does not turn off all warnings is not obvious). 

So I think the example does not show the actual problem, assuming a difference between 1.9.6 and later should have been visible.

**Comment by TommyPec** [comment]
I'll re-check with 1.9.6, but the point isn't just to not have warnings, it's about to get the right documentation. Unfortunately I can't run 1.9.6 without recompiling it or using a container.

Aside the warning, according to the documentation
> If the using-declaration refers to a constructor of a direct base of the class being defined (e.g. using Base::Base;), all constructors of that base (ignoring member access) are made visible to overload resolution when initializing the derived class.

It isn't defining new functions (or constructors), so I'd expect to not find them in the documentation or, better, to find documented the constructors of the derived class. Problem is: the base class might have more than one constructor, and the `using` allows to do overload resolution on all of them.

[Here](https://en.cppreference.com/w/cpp/language/using_declaration) there is a good explanation in the section "Inheriting constructors". `struct D` does not have constructors, but it does have the base class ones via overload resolution.
 
Honestly, I have no idea how much this is going to be a pain to code.

PS: in ns-3 we do activate *all* the warnings in our CI, and no merge request is merged if there are warnings. We're kinda pedantic... but sometimes the script to catch the warnings is bugged and something slips past.

**Comment by albert-github** [comment]
Are you 100% sure that the CI runs doxygen 1.9.6, did you see evidence of it in the generated files.?

The header file (in `HTML_HEADER`)  you use looks like still to have the line:
```
ns3_html_theme/ns3_doxy_header.html
```
in it so should be OK.

Something worrying though is the comment in the mentioned file it says:
```
<!-- ns-3 doxygen header, based on
     HTML header for doxygen 1.8.3.1
     Verified compatible with 1.8.6
-->
```
is this correct? and does this still work with doxygen 1.9.6?

Other way to see in your CI is calling doxygen once with `doxygen -v` so you know which version you are using (might be that you call doxygen with a path etc. and in that case the call `doxygen -v` should of course be adjusted accordingly).

**Comment by TommyPec** [comment]
Absolutely sure:

```
.doc:
  stage: documentation
  before_script:
    - pacman-key --init
    - pacman -Syu --noconfirm
      base-devel ninja cmake python ccache gsl gtk3 boost openmpi openssh
      graphviz imagemagick texlive-basic texlive-bin texlive-binextra texlive-latexextra
      texlive-fontutils texlive-fontsrecommended python-sphinx
    #  doxygen
    # dia is archived
    - pacman --noconfirm -U https://archive.archlinux.org/packages/d/dia/dia-0.97.3-9-x86_64.pkg.tar.zst
    # temporary revert to Doxygen 1.9.6
    - pacman --noconfirm -U https://archive.archlinux.org/packages/d/doxygen/doxygen-1.9.6-1-x86_64.pkg.tar.zst
    # no policy is a good policy.
    - mv /etc/ImageMagick-7/policy.xml /etc/ImageMagick-7/policy.xml.bak
    # - sed -i "s/EPS,PDF,//g" /etc/ImageMagick-7/policy.xml
    # - sed -i "s/none/read\ |\ write/g" /etc/ImageMagick-7/policy.xml
  image: archlinux
```
