### ISSUE TITLE
Exiting with exit code 1, no warnings, no errors when executed on Github Action

### ISSUE THREAD

**Issue by fbramato** [doxygen/doxygen#10866]
**Describe the bug**
Doxygen is executed and exits immediately, no warnings, no errors.

**Screenshots**

![image](https://github.com/doxygen/doxygen/assets/118736163/e2abad7b-d65d-419e-92b7-1967495e9dfa)

**To Reproduce**
I'm running a Github Action Workflow

```
# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Doxygen
        uses: ssciwr/doxygen-install@v1
        
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          tools: composer

      - name: Setup Node
        uses: actions/setup-node@v4
    
      - name: NPM install
        run: npm install

      - name: Composer install
        run: composer install

      - name: Run Doxygen
        run: |
          doxygen bvi106php-r01BackEnd.Doxyfile
          doxygen bvi106vue-r01FrontEnd.Doxyfile
``` 

**Expected behavior**
Should run and creates the documentation.

**Version**
1.10
Tested on ubuntu-latest and windows-latest on Github Workflow, and via act (https://github.com/nektos/act) locally 

**Stack trace**
None

**Additional context**
Tested the same Doxyfile on Windows 11 and WSL, it works, generate correctly the documentation portal as expected.
