### ISSUE TITLE
macro use treated as function declaration (Origin: bugzilla #736401)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5618]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.8* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[example.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug736401_285813_example.zip/download/download)_ (ID 285813)

On 2014-09-10 10:15:29 +0000, korbel.jak@gmail.com wrote:

    Created attachment 285813
    Example code & config used to reproduce the bug.
    
    I am using preprocessor macro to create a c structure type, which I then use
    to instantiate one static variable. I want to document the macro and the
    variable, but I am getting doxygen warnings, and in my html output, there is
    a new function called like the macro call, which warns about @return not
    defined.
    
    (You can see the attachement with the example code & config.)
    
    I tried to manipulate with preprocessing config options, but with no
    success, if I want the variable to be documented.

**Comment by joenio** [comment]
bug verified on doxyparse also, follow testcase details.

C code `example.c`:

```c
#include <stdio.h>

SOME_EXTERNAL_MACRO(1);

int main(int argc, char **argv) {
  printf("hello");
}
```

when I run `doxyparse example.c` the output list `SOME_EXTERNAL_MACRO` as a defined function on sample code, see `doxyparse` output:

```yaml
example.c:
  "example.c":
    defines:
      - "SOME_EXTERNAL_MACRO()":
          type: function
          line: 5
          protection: public
          lines_of_code: 1
          parameters: 1
          conditional_paths: 0
      - "main(int,char **)":
          type: function
          line: 7
          protection: public
          lines_of_code: 3
          parameters: 2
          conditional_paths: 0
```

`SOME_EXTERNAL_MACRO()` isn't defined on `example.c` at all but `doxygen` internals was detecting that as member of the code, I'm investigating that but I appreciate any help to give some direction where fix this.

Thanks!

**Comment by albert-github** [comment]
I think doxygen sees  `SOME_EXTERNAL_MACRO()` (as indicated) as a function, not as the implementation but as the prototype. 
Compare this with the output of:
```
#include <stdio.h>

SOME_EXTERNAL_MACRO(1);

int main(int argc, char **argv);
```

I think the output as is is OK (only minor flaw might be that the used argument definition is a number and not a real argument prototype).

**Comment by joenio** [comment]
thanks for the tip @albert-github, you are right, doxygen sees `SOME_EXTERNAL_MACRO()` as prototype, I added a new check verification on doxyparse using `MemberDef->isPrototype()` function and the output on your code example confirm it, see `prorotype: yes`:

```yaml
using_macro.h:
  "using_macro.h":
    defines:
      - "SOME_EXTERNAL_MACRO()":
          type: function
          line: 3
          protection: public
          lines_of_code: 1
          parameters: 1
          prototype: yes
          conditional_paths: 0
      - "main(int,char **)":
          type: function
          line: 5
          protection: public
          lines_of_code: 3
          parameters: 2
          prototype: yes
          conditional_paths: 0
```

I'm going to add this new information on doxyparse output indicating when a prototype is identified.
